status = [
  "Build aarch64 / build (ubuntu-latest, nightly)",
  "Build aarch64 / build (macOS-latest, nightly)",
  "Build x86_64 / build (ubuntu-latest, nightly)",
  "Build x86_64 / build (macOS-latest, nightly)",
  "Format check / build (ubuntu-latest, nightly)",
]
delete_merged_branches = true
timeout_sec = 7200
