[package]
name = "rusty-loader"
version = "0.2.6"
authors = ["Stefan Lankes <slankes@eonerc.rwth-aachen.de>", "Colin Finck <colin.finck@rwth-aachen.de>"]
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2021"

[features]
aarch64-qemu-stdout = []    # Output to special qemu address 0x3F20_1000 instead of trying to use uart

[dependencies]
bitflags = "1.3"
goblin = { version = "0.4", default-features = false, features = ["elf64", "elf32", "endian_fd"] }

[target.'cfg(target_arch = "x86_64")'.dependencies]
multiboot = "0.7"
x86 = { version = "0.44", default-features = false }

[build-dependencies]
target_build_utils = "0.3"

[profile.dev]
opt-level = 1  # `opt-level = 0` makes bootloader to large for bootstrapping

[profile.release]
lto = true
codegen-units = 1
