name: Clippy

on:
  push:
    branches:
      - master
      - staging
      - trying
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Install NASM
        run: |
          sudo apt-get update
          sudo apt-get install nasm
      - uses: actions/checkout@v2
      - name: Rustup (apply rust-toolchain.toml)
        run: rustup show
      - name: Clippy
        run: cargo clippy -- -D warnings
